
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>

namespace facebook {
namespace react {

extern const char RNCPickerComponentName[] = "RNCPicker";

class RNCPickerProps : public ViewProps {
  public:
    RNCPickerProps() = default;

    RNCPickerProps(const PropsParserContext &context, const RNCPickerProps &sourceProps, const RawProps &rawProps)
        : ViewProps(context, sourceProps, rawProps) {}
};

using RNCPickerShadowNode = ConcreteViewShadowNode<
    RNCPickerComponentName,
    RNCPickerProps,
    ViewEventEmitter>;

class RNCPickerComponentDescriptor final
    : public ConcreteComponentDescriptor<RNCPickerShadowNode> {
  public:
    RNCPickerComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};

} // namespace react
} // namespace facebook
