#pragma once

/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

#include "RNOHCorePackage/ComponentBinders/ViewComponentJSIBinder.h"

namespace rnoh {
class RNCPickerJSIBinder : public ViewComponentJSIBinder {
  protected:
    facebook::jsi::Object createNativeProps(facebook::jsi::Runtime &rt) override {
        auto object = ViewComponentJSIBinder::createNativeProps(rt);
        object.setProperty(rt, "items", true);
        object.setProperty(rt, "selectedIndex", true);
        object.setProperty(rt, "selectionColor", true);
        object.setProperty(rt, "color", true);
        object.setProperty(rt, "textAlign", true);
        object.setProperty(rt, "numberOfLines", true);
        object.setProperty(rt, "fontSize", true);
        object.setProperty(rt, "fontWeight", true);
        object.setProperty(rt, "fontStyle", true);
        object.setProperty(rt, "fontFamily", true);
        object.setProperty(rt, "testID", true);
        object.setProperty(rt, "themeVariant", true);
        object.setProperty(rt, "enabled", true);
        object.setProperty(rt, "fakeProp", "Object");
        return object;
    }

    facebook::jsi::Object createBubblingEventTypes(facebook::jsi::Runtime &rt) override {
        facebook::jsi::Object events(rt);
        events.setProperty(rt, "topChange", createBubblingCapturedEvent(rt, "onChange"));
        return events;
    }

    facebook::jsi::Object createDirectEventTypes(facebook::jsi::Runtime &rt) override {
        facebook::jsi::Object events(rt);
        return events;
    }
};
} // namespace rnoh
